Update: prepared for docker deployment 2

diff --git a/.github/workflows/deploy-compose.yml b/.github/workflows/deploy-compose.yml
--- a/.github/workflows/deploy-compose.yml
+++ b/.github/workflows/deploy-compose.yml
@@ -3,7 +3,6 @@ name: Deploy to Production Server with Docker Compose
 on:
   push:
     branches:
-      - main # Trigger on push to the main branch
       - staging # Trigger on push to the staging branch
   workflow_dispatch:
 
@@ -58,8 +57,14 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
 
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_MONOREPO_TOKEN }}
+
       - name: Build and Push Docker Image for ${{ matrix.service.name }}
-        if: ${{ matrix.service.if }} # Only run this step if the service changed
+        if: ${{ matrix.service.if_changed == 'true' }}
         uses: docker/build-push-action@v4
         with:
           context: ${{ matrix.service.path }}
@@ -73,7 +78,6 @@ jobs:
   deploy:
     needs: build-and-push
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
     steps:
       - name: Deploy to Server
         uses: appleboy/ssh-action@master
@@ -82,17 +86,14 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            # Determine the branch we are deploying
-            BRANCH_NAME=${{ github.ref_name }}
-            echo "Deploying branch: $BRANCH_NAME"
+            set -e # Exit immediately if a command fails
 
             # Navigate to the application directory on the server
             cd /home/ubuntu/paservices
 
-            # Pull the latest code from the repository
-            echo "Pulling latest code from origin/$BRANCH_NAME..."
-            git checkout $BRANCH_NAME
-            git pull origin $BRANCH_NAME
+            echo "Pulling latest code from origin/staging..."
+            git checkout staging
+            git pull origin staging
 
             # Export all secrets as environment variables
             # This makes them available to the docker-compose command
@@ -112,7 +113,6 @@ jobs:
             export DATA_CAPTURE_M2M_CLIENT_ID='${{ secrets.DATA_CAPTURE_M2M_CLIENT_ID }}'
             export DATA_CAPTURE_M2M_CLIENT_SECRET='${{ secrets.DATA_CAPTURE_M2M_CLIENT_SECRET }}'
             export RAPID_API_KEY='${{ secrets.RAPID_API_KEY }}'
-
 
             # Log in to Docker Hub
             echo ${{ secrets.DOCKERHUB_MONOREPO_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
